puckeditor/puck

.gitignore, packages/create-puck-app/templates/next/database.json
=> feat: add default index page data to next template

.github/workflows/ci.yml, package.json, recipes/next/database.json, recipes/next/package.json
Follow on from https://github.com/measuredco/puck/pull/59#issuecomment-1714377921.
Closes #48.
CC @abhishek276533
=> Build next recipe as part of CI

README.md
=> docs: add badges and Discord to README

README.md
Follow on from #37. Part of #100.
=> doc: document the DropZone component

packages/core/lib/__tests__/reducer.spec.tsx, packages/core/lib/reducer.ts
Configures jest and adds tests for the reducer added in #37 
Some overlap with #111 PR, as both configure jest (CC @yuddomack)
Closes #89
=> Configure jest and add tests for reducer

package.json
=> build: specify >=18 Node engine

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Missed some comments in #181 that came in after merge, apologies @anglepoised!
=> Fix links in Code of Conduct and address further CONTRIBUTING comments

apps/demo/next.config.js, packages/core/components/ExternalInput/index.tsx, packages/core/components/InputOrGroup/fields/ExternalField/index.tsx
Final tweaks to external fields based on field-testing. See commits for changelog.
=> Final tweaks to external field

CHANGELOG.md, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/plugin-heading-analyzer/package.json
Summary:
* New resolveData API
* Next.js recipe now supports static rendering
* Make fields more consistent
* Various deprecations
* Bug fixes & performance improvements
=> release: v0.11.0

.github/workflows/publish-canary.yml, .github/workflows/publish.yml, CHANGELOG.md, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/create-puck-app/scripts/generate.js, packages/create-puck-app/templates/.gitignore, packages/plugin-heading-analyzer/package.json, recipes/next/.gitignore, scripts/publish.sh
Merging releases v0.11.1 and v0.11.2. Use squash to prevent triggering a new release.
=> Merge patch releases

packages/create-puck-app/index.js
- clean unnecessary awaits
- initialize git optionally
- prevent Windows's git crash due to commits with single quotes
=> 👌 IMPROVE(create-puck-app): enhancements

packages/core/components/InputOrGroup/index.tsx
Fixes issues with debounce rendering, demonstrated in https://github.com/devkiran/test-puck-editor/tree/main
=> fix: ensure field debounce doesn't sporadically lock preview update

CHANGELOG.md, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/plugin-heading-analyzer/package.json
Merge release notes and version numbers from releases/v0.11.3. Will not trigger a subsequent release on merge.
=> Merge v0.11.3 release

apps/demo/app/[...puckPath]/client.tsx, apps/demo/app/layout.tsx, apps/demo/config/blocks/Blank/index.tsx, apps/demo/config/blocks/ButtonGroup/index.tsx, apps/demo/config/blocks/Card/index.tsx, apps/demo/config/blocks/Columns/index.tsx, apps/demo/config/blocks/FeatureList/index.tsx, apps/demo/config/blocks/Flex/index.tsx, apps/demo/config/blocks/Heading/index.tsx, apps/demo/config/blocks/Hero/index.tsx, apps/demo/config/blocks/Logos/index.tsx, apps/demo/config/blocks/Stats/index.tsx, apps/demo/config/blocks/Text/index.tsx, apps/demo/config/blocks/VerticalSpace/index.tsx, apps/demo/config/components/Section/index.tsx, apps/demo/config/index.tsx, apps/demo/config/root.tsx, apps/demo/package.json, apps/demo/puck.config.tsx, apps/demo/tsconfig.json, packages/create-puck-app/templates/.gitignore, packages/plugin-heading-analyzer/src/HeadingAnalyzer.tsx, packages/plugin-heading-analyzer/tsconfig.json, yarn.lock
This unblocks #221, which introduces the [`exports` API](https://nodejs.org/api/packages.html#subpath-exports).
=> Use TypeScript instead of package imports 

apps/docs/pages/docs/api-reference/plugins/app-state.mdx, packages/core/components/Button/Button.module.css, packages/core/components/IconButton/IconButton.module.css, packages/core/components/IconButton/IconButton.tsx, packages/core/components/InputOrGroup/fields/ArrayField/styles.module.css, packages/core/components/InputOrGroup/styles.module.css, packages/core/components/MenuBar/index.tsx, packages/core/components/MenuBar/styles.module.css, packages/core/components/Puck/context.tsx, packages/core/components/Puck/index.tsx, packages/core/components/Puck/styles.module.css, packages/core/lib/__tests__/use-puck-history.spec.tsx, packages/core/types/Config.tsx
=> Improve narrow viewport support 2

.github/workflows/ci.yml, packages/create-puck-app/templates/remix/package.json.hbs, recipes/remix/README.md, recipes/remix/app/root.tsx, recipes/remix/app/routes/_index.tsx, recipes/remix/app/routes/edit.tsx, recipes/remix/package.json
=> Remove nojs from remix recipe

CHANGELOG.md, apps/docs/theme.config.tsx, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/plugin-heading-analyzer/package.json
~Was hoping to merge #227, but this PR has conflicts so suggest we defer to next feature release.~
Edit: The above was merged.
=> release: v0.12.0

.github/workflows/publish.yml, apps/docs/components/ReleaseSwitcher/index.tsx, apps/docs/components/ReleaseSwitcher/styles.module.css, apps/docs/package.json, apps/docs/pages/_app.tsx, apps/docs/pages/api/releases.ts, apps/docs/pages/v/[[...fullPath]].tsx, apps/docs/theme.config.tsx, lerna.json, turbo.json, yarn.lock
This PR introduces versioned docs by leveraging Vercel's preview branches and rendering them via an iframe.
=> docs: add versioned docs

packages/core/components/Puck/index.tsx
Helpful hook for override styling.
=> feat: add Puck class to outer div

CHANGELOG.md, apps/docs/package.json, apps/docs/public/robots.txt, apps/docs/theme.config.tsx, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/plugin-heading-analyzer/package.json
Puck v0.13.0 is out and introduces some of our most powerful APIs yet, enabling completely custom interfaces.
1. [**Custom interfaces**](https://puckeditor.com/docs/extending-puck/custom-interfaces): Take complete control of the Puck UI with the new custom interface APIs.
2. [**Object fields**](https://puckeditor.com/docs/api-reference/configuration/fields/object): Represent objects as fields with the new `object` field type.
3. [**DropZone restrictions**](https://puckeditor.com/docs/api-reference/components/drop-zone#allow): The new `allow` and `disallow` props allow you to restrict which components can be dropped into DropZones.
4. [**New plugin API (Breaking Change)**](https://puckeditor.com/docs/extending-puck/plugins): The plugin API has been updated to align with the new custom …
=> Create release v0.13.0

recipes/next/app/layout.tsx, recipes/next/app/puck/[...puckPath]/page.tsx
Closes #319 
I guess this issue could also exist in the Remix recipe, but don't know enough about that to change anything there.
=> feat: move CSS import in Next.js recipe

packages/core/lib/use-puck.ts
exposed history state in usePuck hook 
#317 is fixed
=> exposed history state in usePuck hook

apps/demo/config/blocks/ButtonGroup/index.tsx, apps/demo/config/blocks/VerticalSpace/index.tsx, packages/core/components/ComponentList/index.tsx, packages/core/components/Drawer/index.tsx, packages/core/components/DropZone/index.tsx, packages/core/components/LayerTree/index.tsx, packages/core/components/Puck/components/Outline/index.tsx, packages/core/components/Puck/index.tsx, packages/core/lib/use-component-list.tsx, packages/core/types/Config.tsx
Provides the option to add a custom label to a component. The label is optional; by default, it will display the component type.
=> Feature: add label params to component config

packages/core/components/DragDropContext/index.tsx, packages/core/components/Draggable/index.tsx, packages/core/components/DraggableComponent/styles.module.css, packages/core/components/Droppable/index.tsx, packages/core/components/Puck/components/Preview/index.tsx, packages/core/components/Puck/components/Preview/styles.module.css, packages/core/package.json, yarn.lock
Follow-ups from #353. See commits for details.
=> Post viewport follow-ups

apps/demo/app/custom-ui/[...puckPath]/client.tsx, apps/docs/components/Preview/index.tsx, apps/docs/pages/docs/api-reference/components/puck.mdx, packages/core/components/DragDropContext/index.tsx, packages/core/components/Draggable/index.tsx, packages/core/components/DraggableComponent/index.tsx, packages/core/components/DraggableComponent/styles.module.css, packages/core/components/Droppable/index.tsx, packages/core/components/LayerTree/index.tsx, packages/core/components/Puck/components/Canvas/index.tsx, packages/core/components/Puck/components/Canvas/styles.module.css, packages/core/components/Puck/components/Preview/index.tsx, packages/core/components/Puck/components/Preview/styles.module.css, packages/core/components/Puck/context.tsx, packages/core/components/Puck/index.tsx, packages/core/components/Puck/styles.module.css, packages/core/components/ViewportControls/index.tsx, packages/core/lib/get-frame.ts, packages/core/lib/use-frame.ts, packages/core/lib/use-placeholder-style.ts, packages/core/package.json, packages/core/types/IframeConfig.tsx, packages/plugin-heading-analyzer/src/HeadingAnalyzer.tsx, yarn.lock
Further tweaks following #353 #374
=> Post viewport follow-ups (pt. 2)

apps/docs/pages/docs/api-reference/components/puck-preview.mdx, packages/core/components/LayerTree/index.tsx, packages/core/components/Puck/components/Canvas/styles.module.css, packages/core/components/ViewportControls/styles.module.css, packages/core/lib/get-frame.ts, packages/core/lib/use-frame.ts, packages/core/lib/use-placeholder-style.ts, packages/plugin-heading-analyzer/src/HeadingAnalyzer.tsx
=> Post viewport tweaks (pt. 3)

apps/demo/config/blocks/Hero/index.tsx, apps/docs/pages/docs/api-reference/functions/use-puck.mdx, packages/core/components/ExternalInput/index.tsx, packages/core/components/InputOrGroup/fields/ArrayField/index.tsx, packages/core/components/InputOrGroup/fields/ArrayField/styles.module.css, packages/core/lib/use-placeholder-style.ts, packages/core/lib/use-puck.ts, packages/plugin-heading-analyzer/src/HeadingAnalyzer.tsx, scripts/publish.sh
See commits for details.
Closes #210, closes #358
=> Misc changes

apps/demo/app/[...puckPath]/client.tsx, apps/demo/app/custom-ui/[...puckPath]/client.tsx, apps/demo/config/components/Footer/index.tsx, apps/demo/config/components/Header/index.tsx, apps/demo/config/index.tsx, apps/demo/config/root.tsx, apps/docs/pages/docs/api-reference/configuration/fields/array.mdx, apps/docs/pages/docs/api-reference/configuration/fields/external.mdx, apps/docs/pages/docs/api-reference/configuration/fields/number.mdx, apps/docs/pages/docs/integrating-puck/_meta.json, apps/docs/pages/docs/integrating-puck/viewports.mdx, packages/core/components/DropZone/context.tsx, packages/core/components/DropZone/index.tsx, packages/core/components/DropZone/types.ts, packages/core/components/Puck/components/Preview/index.tsx, packages/core/components/Puck/context.tsx, packages/core/components/Puck/index.tsx, packages/core/components/Render/index.tsx, packages/core/components/ServerRender/index.tsx, packages/core/lib/resolve-all-data.ts, packages/core/reducer/index.ts, packages/core/types/Config.tsx, packages/field-contentful/package.json, packages/tsup-config/index.ts, yarn.lock
=> Further misc changes

packages/core/components/Puck/components/Canvas/index.tsx, packages/core/components/Puck/index.tsx, packages/core/components/Puck/styles.module.css
Based on further canary testing in the wild.
=> Pre release fixes (pt. 2)

apps/docs/releases.json, apps/docs/theme.config.tsx, packages/field-contentful/package.json, packages/plugin-heading-analyzer/package.json
A couple of things that were missed, and removal of a peer-dep causing warnings during install.
=> Post release tidy up

packages/core/components/Puck/index.tsx, packages/core/components/Puck/styles.module.css
Fix an issue affected applications generated with the Next recipe. It's unclear why this isn't impacting other environments, but this fix should work across the board.
=> fix: prevent grid-related layout issues in some environments

apps/docs/pages/docs/index.mdx, packages/core/package.json, yarn.lock
Reuse host styles from <link> tags instead of reloading them as part of [auto-frame-component@0.1.2](https://github.com/measuredco/auto-frame-component/commit/d5251e3cb1f374d2c25c8fd0f110dde08ba82441).
=> Improve iframe loading performance

packages/core/package.json, yarn.lock
Fix: https://github.com/measuredco/dnd/commit/4cba1d137fe9b805575150a10c2afd0ef2ab4bd8
Closes #428
=> fix: fix drag-and-drop when entire Puck component used inside an iframe

apps/demo/config/index.tsx, packages/core/components/MenuBar/index.tsx, packages/core/components/Puck/context.tsx, packages/core/components/Puck/index.tsx
Turns out this was never implemented!
=> fix: fix defaultProps for root

packages/core/components/DropZone/index.tsx, packages/core/components/LayerTree/index.tsx, packages/core/components/Puck/index.tsx
=> fix: fix crash if component in data is missing from config

apps/docs/pages/docs/api-reference/components/puck.mdx, packages/core/components/Puck/index.tsx, packages/core/lib/__tests__/use-history-store.spec.tsx, packages/core/lib/use-history-store.ts
Addresses https://github.com/measuredco/puck/issues/492
=> feat: add initialHistories prop to Puck

packages/core/index.ts
Fixes https://github.com/measuredco/puck/issues/518
=> fix: export History type

packages/core/components/AutoFrame/index.tsx
Fixing the issue where not all styles are synced to the iFrame. Adding sync functionality of attributes from HTML and Body tags to iFrame.
=> #543 improve resiliency of iframe css loading

apps/demo/package.json, apps/docs/package.json, packages/core/package.json, packages/core/reducer/__tests__/data.spec.tsx, packages/core/reducer/__tests__/state.spec.tsx, packages/core/tsconfig.json, packages/create-puck-app/templates/next/package.json.hbs, packages/field-contentful/package.json, packages/plugin-heading-analyzer/package.json, packages/tsup-config/package.json, recipes/next/package.json, yarn.lock
=> build: upgrade to typescript@5.5.4

packages/core/components/Puck/index.tsx, packages/core/lib/__tests__/insert-component.spec.tsx, packages/core/lib/insert-component.ts, packages/core/reducer/actions.tsx, packages/core/reducer/data.ts
Call `resolveData` on components when a new item is dragged onto the canvas.
Closes #511
=> feat: call resolveData when new item inserted

apps/demo/app/custom-ui/[...puckPath]/client.tsx, packages/core/components/ComponentList/index.tsx, packages/core/components/DraggableComponent/index.tsx, packages/core/components/DropZone/index.tsx, packages/core/components/Puck/components/Fields/index.tsx, packages/core/lib/get-permissions.ts, packages/core/lib/resolve-permissions.ts, packages/core/lib/use-puck.ts, packages/core/types/Config.tsx
=> feat: adding resolve permissions

packages/core/components/Puck/components/Fields/index.tsx
=> fix: resolve fields when switching between items of same type

apps/docs/releases.json, apps/docs/theme.config.tsx
=> Add v0.16 release to site

apps/docs/pages/docs/integrating-puck/server-components.mdx, packages/core/rsc.tsx
Add missing RSC exports and rewrite the RSC documentation with real examples.
=> Add missing RSC export and rewrite RSC docs

apps/demo/config/blocks/Hero/index.tsx, packages/core/components/AutoField/index.tsx, packages/core/index.ts
=> Remove internal AutoField components from bundle

apps/docs/pages/docs/api-reference/data.mdx
Addresses [697](https://github.com/measuredco/puck/issues/697)
=> Fix: Broken link in data.mdx

packages/core/components/AutoField/fields/DefaultField/index.tsx
Addresses https://github.com/measuredco/puck/issues/694
=> fix: remove leading zeros in NumberField

apps/docs/pages/docs/api-reference/configuration/component-config.mdx, packages/core/components/Puck/components/Fields/index.tsx, packages/core/lib/use-parent.ts, packages/core/types/Config.tsx
Enable resolveFields to access parent data, and attempt to fix #670
=> Enable resolveFields to access parent data

packages/core/components/AutoField/fields/RadioField/index.tsx, packages/core/components/AutoField/fields/SelectField/index.tsx, packages/core/lib/safe-json-parse.ts
=> fix: respect existing value type in radios and select fields

apps/docs/components/Home/index.tsx, apps/docs/components/Home/styles.module.css, apps/docs/pages/_meta.js, packages/core/components/Button/Button.tsx, packages/core/lib/filter-data-attrs.ts
Add bolder Measured support CTAs to docs site, with direct link to new calendar link.
=> docs: add new support CTAs to docs site

packages/core/components/AutoField/fields/ArrayField/index.tsx, packages/core/components/AutoField/fields/ObjectField/index.tsx
=> fix: use correct label for array and object subfields

packages/core/components/AutoField/fields/DefaultField/index.tsx, packages/core/components/AutoField/index.tsx
=> fix: respect min/max for freeform input in number field

CHANGELOG.md, apps/docs/package.json, apps/docs/releases.json, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/field-contentful/package.json, packages/plugin-emotion-cache/package.json, packages/plugin-heading-analyzer/package.json
=> Merge 0.17.2 release

packages/core/components/Drawer/index.tsx, packages/core/components/DropZone/index.tsx
=> Solve SSR issues with new dnd engine

packages/core/components/DropZone/index.tsx
This never worked.
Closes #799
=> fix: respect allow prop for existing items

CHANGELOG.md, apps/docs/package.json, apps/docs/releases.json, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/field-contentful/package.json, packages/plugin-emotion-cache/package.json, packages/plugin-heading-analyzer/package.json
Merge patch release notes into main branch.
=> Merge 0.17.4 release notes to main

packages/core/components/Puck/components/Fields/index.tsx
Might address #827, but an improvement regardless
=> fix: don't access selectedItem if undefined right after drop

apps/demo/config/blocks/Grid/index.tsx, packages/core/components/DraggableComponent/index.tsx
Address the ResizeObserver loop error by unregistering the observer during a drag.
Closes #835
=> Address ResizeObserver loop error

packages/core/components/Puck/components/Preview/index.tsx, packages/core/lib/bubble-pointer-event.ts, packages/core/lib/dnd/NestedDroppablePlugin.ts
=> fix: address ownerDocument permission error in Firefox

packages/core/components/DropZone/index.tsx, packages/core/components/Puck/components/Preview/index.tsx, packages/core/components/Render/index.tsx, packages/core/components/ServerRender/index.tsx, packages/core/index.ts, packages/core/types/Config.tsx
Closes #853 and addresses related type issues.
=> Fix renderDropZone for root render

apps/demo/config/components/Header/styles.module.css, apps/demo/config/components/Section/styles.module.css, apps/docs/components/FooterActions/styles.module.css, apps/docs/components/Home/styles.module.css, apps/docs/components/Preview/styles.module.css, apps/docs/components/ReleaseSwitcher/styles.module.css, packages/core/components/ActionBar/styles.module.css, packages/core/components/AutoField/styles.module.css, packages/core/components/Button/Button.module.css, packages/core/components/ComponentList/styles.module.css, packages/core/components/DragDropContext/index.tsx, packages/core/components/ExternalInput/styles.module.css, packages/core/components/LayerTree/styles.module.css, packages/core/components/OutlineList/styles.module.css, packages/core/components/Puck/styles.module.css, packages/core/components/SidebarSection/styles.module.css, packages/core/components/ViewportControls/styles.module.css, packages/core/lib/get-deep-dir.ts, packages/core/package.json, yarn.lock
Addresses issues with RTL support, prompted by #844:
Closes #844, closes #595
=> Fix RTL support

packages/core/components/AutoField/index.tsx, packages/core/types/API/Overrides.ts, packages/core/types/Fields.ts
=> refactor: reorder FieldType generics so TS can infer type

apps/docs/pages/docs/api-reference/components/puck.mdx
Pull request that fixes issue #874
=> Fix error in headerTitle documentation

apps/docs/pages/docs/api-reference/components/drop-zone.mdx
Pull request that fixes issue #907
=> Remove 'Restrictions' section on DropZone's page

apps/demo/config/blocks/Text/index.tsx, apps/docs/pages/docs/api-reference/fields/base.mdx, packages/core/components/AutoField/fields/ArrayField/index.tsx, packages/core/components/AutoField/fields/DefaultField/index.tsx, packages/core/components/AutoField/fields/ExternalField/index.tsx, packages/core/components/AutoField/fields/ObjectField/index.tsx, packages/core/components/AutoField/fields/RadioField/index.tsx, packages/core/components/AutoField/fields/SelectField/index.tsx, packages/core/components/AutoField/fields/TextareaField/index.tsx, packages/core/components/AutoField/index.tsx, packages/core/types/Fields.ts
=> feat: label icon field param

packages/core/components/AutoField/fields/ArrayField/index.tsx, packages/core/components/Sortable/index.tsx, packages/core/lib/dnd/dnd-kit/safe.ts, packages/core/lib/dnd/use-sensors.ts
Fix nested arrays and address a style issue.
Went for a different approach to #927, using dnd-kit's handleRef instead of blocking the event propagation, which was a hack.
Closes #926.
=> Fix nested arrays, and address style issue

packages/core/components/DraggableComponent/index.tsx
closes https://github.com/measuredco/puck/issues/656
(removed "Header" content in screen recordings below to replicate issue)
before screen recording:
https://github.com/user-attachments/assets/024c51da-b942-4a4d-b1bb-42537c8c4bb2
after screen recording:
https://github.com/user-attachments/assets/56004b5f-a857-401b-b689-6f48e1bf163d
=> fix: actionbar clipping past top bound

packages/core/lib/dnd/PointerSensor.ts
Attempt at fixing an issue where the item would stick to the window during an aborted drag. Not an ideal solution, but want to see if it helps mitigate.
Issue reproducible with both current and latest versions of new dnd-kit, regardless of forked pointer sensor.
Some users encounter on every drag on Windows, but I was able to reproduce with the following steps on macOS:
1. Click down on the first item
2. Very quickly move the pointer and release
3. Scroll
The dragged item sticks to the window
https://github.com/user-attachments/assets/fbcf59f8-119c-4ce4-9278-407ed3147a8d
The dragged item does not stick to the window, and the drag is cancelled
=> fix: prevent item from sticking to window

package.json, packages/core/components/Drawer/styles.module.css, packages/core/components/DropZone/index.tsx, packages/core/components/Puck/components/Fields/index.tsx, packages/core/components/Puck/index.tsx, packages/core/lib/dnd/NestedDroppablePlugin.ts, packages/core/lib/global-position.ts, packages/core/store/slices/fields.ts, scripts/e2e/smoke.mjs, yarn.lock
Closes #1025, closes #1024, closes #1027, closes #1029
=> Fix various bugs with slots

packages/core/components/DraggableComponent/index.tsx, packages/core/lib/accumulate-transform.ts
=> fix: account for transforms in overlays

packages/core/lib/get-changed.ts
=> fix: deeply check items before populating resolveData changed

packages/create-puck-app/templates/react-router/package.json.hbs
=> chore: fix typo in react-router package.json

packages/core/components/Sortable/index.tsx, packages/core/lib/dnd/use-sensors.ts
=> fix: ensure array items can be opened on mobile

packages/core/components/Puck/styles.module.css
=> fix: prevent horizontal scroll on touch  devices

packages/core/lib/__tests__/migrate.spec.tsx, packages/core/lib/migrate.ts
=> fix: handle multiple slots in migrate function

packages/core/lib/data/flatten-node.ts, recipes/react-router/package.json, yarn.lock
Address issues impacting RR7 issues, including:
* An import issue related to the flat package
* A Puck development issue, caused by multiple versions of React
Closes #1089
=> Address issues impacting RR7 recipe

packages/core/reducer/actions/__helpers__/index.tsx, packages/core/reducer/actions/__tests__/replace.spec.ts, packages/core/reducer/actions/replace.ts
=> fix: tidy internal index when array slots removed

packages/core/components/LayerTree/index.tsx
=> fix: respect slot label in outline panel

packages/create-puck-app/index.js
=> chore: use list for recipe question

packages/core/components/AutoFrame/index.tsx
=> fix: prevent iframe hanging when stylesheets empty

packages/core/components/DropZone/context.tsx, packages/core/components/DropZone/index.tsx, packages/core/components/Puck/index.tsx
=> fix: retain DropZone content in interactive mode

packages/core/components/DragDropContext/index.tsx, packages/core/components/DropZone/context.tsx, packages/core/components/DropZone/index.tsx
=> fix: don't revert custom Drawer.Items during drag

packages/core/lib/use-puck.ts, packages/core/types/Utils.tsx
=> fix: respect user generic in usePuck hook

apps/docs/pages/docs/api-reference/functions/migrate.mdx, apps/docs/pages/docs/api-reference/functions/transform-props.mdx, packages/core/lib/__tests__/transform-props.spec.tsx
=> docs: clarify config requirement in migrate and transformProps functions

packages/core/components/AutoField/index.tsx
=> chore: prevent custom fields from losing focus on initial keydown
