puckeditor/puck

apps/demo/app/configs/custom/blocks/Hero/index.tsx, apps/demo/app/configs/custom/blocks/Hero/quotes.ts
The [quotes API](https://github.com/lukePeavey/quotable/tree/master) we were using in the demo went down. Unsure if related to our sudden surge of traffic. If it is, apologies to maintainer @lukePeavey.
This PR replaces the API call with some hardcoded quotes.
=> docs: replace quotes API in demo with hardcoded quotes

.github/workflows/ci.yml
Adds ci file which checks lint & formatting along with build for pull requests & direct push
@chrisvxd Let me know if there are any changes you want
=> ci: Add workflow file for pull requests

README.md, packages/core/components/InputOrGroup/index.tsx, packages/core/index.ts, packages/core/types/Config.tsx
This PR proposes an implementation for custom field support, allowing users to extend the included field types.
* Adds new `custom` option to field `type`
* Adds new `render` param, accepting the following options:
- **field** (`Field`): Field configuration
- **name** (`string`): Name of the field
- **value** (`any`): Value for the field
- **onChange** (`(value: any) => void`): Callback to change the value
- **readOnly** (`boolean` | `undefined`): Whether or not the field should be in readOnly mode
* Exposes `<FieldLabel>` component which accepts the `children`, `label` and `icon` props (currently undocumented)
If we like this direction, suggest we mark as Ready for Review.
Closes #57 
```tsx
import { FieldLabel } from "@measured/puck";
export const MyComponent: ComponentConfig = { …
```
=> Add support for custom fields

README.md
Hi, this is a great project! 
Had some minor issues with the example code in README but i figured them out.
The example is lacking the `content` and `root` properties in the `initialData`. (so i get a TypeError for trying to read title of undefined root).
Also added the neccessary css import.
A better fix would probably be to make them optional instead of just empty objects. Happy to close this one and work on that instead if you feel like that would be a more preferable fix.
Cheers!
=> fix the example code in README.md

apps/demo/app/configs/custom/blocks/Hero/index.tsx, packages/core/components/Puck/index.tsx
When using hooks directly inside a render function (rather than a sub-component), React will often complain that we're breaking the rules of hooks.
In main, using `useState` inside a render function would result in a hooks error when adding a component containing hooks:
> Error: Rendered more hooks than during the previous render.
Or this when removing a component containing hooks:
> Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
This occurs is because React expects the render function to start with an uppercase letter. This PR assigns the render function to a constant with an upper case letter to eliminate this issue.
_NB: whilst this PR fixes this issue, but does cause eslint to trip-up because `render` starts with a lower-case …
=> Fix components with hooks

packages/core/components/InputOrGroup/index.tsx, packages/core/components/InputOrGroup/styles.module.css
Specificity was too low on certain definitions, resulting in styles being overridden by user styles.
See example showing missing padding on fieldset due to `fieldset { padding: 0 };` global definition.
=> fix: ensure form styles override global styles

apps/demo/package.json, packages/create-puck-app/templates/next/package.json.hbs, recipes/next/package.json, yarn.lock
Vercel builds have started failing on old next versions: https://github.com/vercel/next.js/issues/49169#issuecomment-1730544814
Upgrading next to fix.
=> Upgrade next to fix vercel builds

.github/workflows/ci.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml
To review, check the logs in this build mention `v0.8.0-canary.HASH` under the "Run release script" step: https://github.com/measuredco/puck/actions/runs/6274146765/job/17038992854?pr=102
=> ci: ensure canary pipeline determines correct version

.github/workflows/publish-canary.yml, .github/workflows/publish.yml
#102 fixed the canary version determination but broke publishing. See https://stackoverflow.com/a/76764356
=> ci: add missing registry-url to GitHub publish action to restore publishing

packages/core/components/Render/index.tsx, packages/core/types/Config.tsx
Fixes two type issues.
Currently the type definition for props being passed into the `render()` function for each component isn't specifying the `id` prop, even though it's always there. This adds it.
**Error**
The types don't currently allow users to nest arrays, even though Puck supports it.
**Props**
```tsx
type Props = {
MyComponent: {
items: {
subItems: { label: string }[];
}[];
};
};
```
**Component**
**Error**
=> Fix various type issues

packages/core/components/Puck/index.tsx, packages/core/components/SidebarSection/styles.module.css
- Adds in styles so Puck doesn't inherit styles from the document body. 
- Fixes an issue where the preview root would inherit/be blocked by the editor frame. 
- I'm just faking the frame with a box shadow.
- Fixes an issue where horizontal scrollbars were always visible for `SidebarSection`'s even when not overflowing.
- Closes #106
=> fix: style clashing with dark mode root element

packages/core/components/OutlineList/index.tsx, packages/core/components/OutlineList/styles.module.css
Some environments were overriding them. Generally we should avoid any element selectors.
=> fix: scope styles in OutlineList

packages/core/components/InputOrGroup/styles.module.css
Some environments reset padding, resulting in broken styles. This PR explicitly adds the padding to override this reset.
=> fix: prevent removal of fieldset padding

packages/core/package.json
Moving to dev dependencies causes `tsup` to bundle the external dependencies where necessary.
This increases the direct bundle size by 72KB but should drop the [328KB react-feather dependency](https://bundlephobia.com/package/@measured/puck@0.8.0-canary.e4cab76).
**Before**
CJS dist/index.js  94.00 KB
**After**
CJS dist/index.js  166.42 KB
Closes #118
=> perf: bundle used react-feather icons only

packages/create-puck-app/templates/next/app/[...puckPath]/page.tsx, recipes/next/app/[...puckPath]/page.tsx
Add missing `?.` optional chaining operator in `export async function generateMetadata` in `recipes/next/app/[...puckPath]/page.tsx`.
```
next-recipe:dev:  ⨯ app/[...puckPath]/page.tsx (31:25) @ root
next-recipe:dev:  ⨯ TypeError: Cannot read properties of undefined (reading 'root')
next-recipe:dev:     at Module.generateMetadata (./app/[...puckPath]/page.tsx:32:29)
next-recipe:dev: digest: "1676022290"
next-recipe:dev:   29 | 
next-recipe:dev:   30 |   return {
next-recipe:dev: > 31 |     title: getPage(path).root.title,
next-recipe:dev:      |                         ^
next-recipe:dev:   32 |   };
next-recipe:dev:   33 | }
next-recipe:dev:   34 |
```
By default the browser attempts to load the `http://localhost:3000/favicon.ico` file but because this file does not exist as a static …
=> fix: add missing optional chaining operator

packages/core/components/InputOrGroup/index.tsx
Currently the `FieldLabel` component expects an optional prop `icon`, but it doesn't render it. This PR should fix that.
=> fix: render `icon` if provided to FieldLabel

packages/core/components/DraggableComponent/styles.module.css
Fixes 2 issues introduced in #132. Using `chore:` commits to avoid polluting diff.
=> Fix issues introduced in #132

packages/core/components/Puck/index.tsx
Added transform to root element so `position: fixed;` elements sit relative to it.
Pictured below is the `apps/demo` with the following added to the `config/root.tsx`.
```tsx
<header
style={{
position: "fixed",
top: 0,
left: 0,
width: "100%",
backgroundColor: "white",
zIndex: 1000,
}}
>
```
It doesn't behave like a `position: fixed;` element normally would due to the scrolling being on an element outside of the one with the transform, but it does allow you to access the editor navigation while you have a fixed navbar.
=> Fix: `position: fixed;` elements escape editor

packages/core/components/Puck/index.tsx
This reverts commit efa4f456458ea8aaab346b21e72dc521e9826279, introduced in #140, which introduces a bug that causes the position of dragged items to lose their position.
=> fix: revert "fix: stop `position: fixed;` elements from escaping editor"

packages/core/components/ExternalInput/index.tsx
it is currently possible for externals to be any kind of JSON data. Only some types can be rendered as react children. This MR checks the type of each property and only renders the ones that are strings
=> fix: limit ExternalInput to only try to render properties that are strings

packages/core/lib/use-puck-history.ts
Please approve #153 first
Some scenarios were tripping up the undo/redo history because of the delta history that used `deep-diff`.
Specifically, this occurred when implementing array field reordering in [#143](https://github.com/measuredco/puck/pull/143#discussion_r1355826936), which caused the undo/redo to corrupt the ordering. Presumably a race condition, as could not easily reproduce during unit tests (which will be added in #143).
It turns out that we were storing the entire object in the forward history (rather than just the diff) anyway, so I decided to strip out `deep-diff` and store the entire object for now. In future, we should revisit delta history.
FYI @Yuddomack
=> refactor: store entire history to improve undo/redo robustness

packages/core/components/DropZone/context.tsx, packages/core/components/Puck/context.tsx, packages/core/components/Puck/index.tsx, packages/core/components/SidebarSection/index.tsx, packages/core/lib/__tests__/is-child-of-zone.spec.tsx, packages/core/lib/__tests__/use-breadcrumbs.spec.tsx, packages/core/lib/get-zone-id.ts, packages/core/lib/is-child-of-zone.ts, packages/core/lib/use-breadcrumbs.ts, packages/core/types/Config.tsx
The expansion state of the LayerTree component is based on the pathData data, which is set by components mounting and calling `registerPath`. However, the pathData object contained selectors with hardcoded indexes for where each item was in their zone. If the item moved, the pathData wouldn't be updated. This was noticed as the LayerTree would sometimes avoid expanding the parent area (i.e. Columns in the demo application) of a selected item because it couldn't find it.
This would not occur for components in the default-zone.
https://github.com/measuredco/puck/assets/985961/8bc051cf-da42-4d04-9ca6-320537ef6f1a
This fix changes the underlying implementation of pathData, going from storing the selectors to the zoneCompound IDs (i.e. `[MyComponent:zone1,MyComponent:zone2]`), and calulating …
=> fix: ensure layer tree consistently shows selected item

packages/core/components/InputOrGroup/fields/ArrayField/index.tsx, packages/core/components/Puck/context.tsx, packages/core/components/Puck/index.tsx, packages/core/components/SidebarSection/index.tsx, packages/core/lib/__tests__/use-puck-history.spec.tsx, packages/core/lib/flush-zones.ts, packages/core/lib/use-breadcrumbs.ts, packages/core/lib/use-puck-history.ts, packages/core/reducer/__tests__/data.spec.tsx, packages/core/reducer/__tests__/state.spec.tsx, packages/core/reducer/actions.tsx, packages/core/reducer/index.ts, packages/core/reducer/state.ts, packages/core/types/Config.tsx
Implements some renames following #153 
* appData -> state _because it's all state really_
* appData.state -> state.ui _because this is UI state only_
* appData.data -> state.data
* `setState` helper -> `setUi`
* `setState` action -> `setUi`
```json
{
"data": {}
"state": {
"leftSideBarVisible": false
}
}
```
```json
{
"data": {}
"ui": {
"leftSideBarVisible": false
}
}
```
```tsx
dispatch({ type: "setState", state: {} });
```
```tsx
dispatch({ type: "setUi", ui: {} });
```
```tsx
dispatch({ type: "set", appData: {} });
```
```tsx
dispatch({ type: "set", state: {} });
```
=> refactor: rename appData to state and appData.state to appData.ui

packages/core/components/Puck/context.tsx, packages/core/lib/use-puck-history.ts, packages/core/types/Config.tsx
#154 resulted in history being stored unexpectedly, such as when the user clicks an empty page.
This does a dumb JSON diff to ensure the object has changed before storing the history. This is likely not that efficient, but will need to be improved when we reintroduced diffed history.
=> chore: don't store history if no diff

README.md, packages/core/components/Puck/index.tsx, packages/core/types/Plugin.ts, packages/plugin-heading-analyzer/src/HeadingAnalyzer.tsx
This PR exposes the application `state` (`AppState`) and dispatcher to:
1. The `renderHeader` method
2. The `renderHeaderActions` method
3. All plugins
This enables users to read and mutate both the application state _and_ the data object.
It also removes the `data` parameter from all APIs, as this is accessible under `state.data`. This is a breaking change, but we're below v1 and are not currently highlighting these.
This example plugin creates a button to toggle the left side-bar:
```jsx
const myPlugin = {
renderRootFields: ({ children, dispatch, state }) => (
<div>
{children}
<button
onClick={() => {
dispatch({
type: "setUi",
ui: { leftSideBarVisible: !state.ui.leftSideBarVisible },
});
}}
>
Toggle side-bar
</button>
</div>
),
};
``` …
=> Expose state and dispatcher via API

packages/core/components/InputOrGroup/fields/ArrayField/index.tsx
=> fix: use empty array when arrayfield value is undefined when creating new array

README.md, apps/demo/app/[...puckPath]/client.tsx, apps/demo/config/blocks/ButtonGroup/index.tsx, apps/demo/config/index.tsx, packages/core/components/ComponentList/index.tsx, packages/core/components/ComponentList/styles.module.css, packages/core/components/DropZone/index.tsx, packages/core/components/InputOrGroup/fields/ArrayField/styles.module.css, packages/core/components/Puck/context.tsx, packages/core/components/Puck/index.tsx, packages/core/lib/__tests__/use-puck-history.spec.tsx, packages/core/lib/use-component-list.tsx, packages/core/types/Config.tsx
This PR introduces:
* a `categories` API for grouping components
* a `renderComponentList` API for both the user and plugins to enable enhancing of the component list (such as for search)
`categories` is a new key on `Config`. 
- **[categoryName]** (`object`)
- **components** (`sting[]`, [optional]): Array containing the names of components in this category
- **title** (`sting`, [optional]): Title of the category
- **visible** (`boolean`, [optional]): Whether or not the category should be visible in the side bar
- **defaultExpanded** (`boolean`, [optional]): Whether or not the category should be expanded in the side bar by default
Example:
```tsx
categories: {
layout: {
components: ["Columns", "Flex", "VerticalSpace"],
},
typography: {
components: ["Heading", "Text"],
},
interactive: { …
```
=> feat: add categories API

README.md, apps/demo/app/[...puckPath]/client.tsx, apps/demo/config/blocks/Hero/index.tsx, apps/demo/config/blocks/Hero/quotes.ts, packages/core/components/DropZone/context.tsx, packages/core/components/DropZone/index.tsx, packages/core/components/ExternalInput/index.tsx, packages/core/components/InputOrGroup/fields/ArrayField/index.tsx, packages/core/components/InputOrGroup/fields/ExternalField/index.tsx, packages/core/components/InputOrGroup/fields/RadioField/index.tsx, packages/core/components/InputOrGroup/fields/SelectField/index.tsx, packages/core/components/Puck/index.tsx, packages/core/index.ts, packages/core/lib/__tests__/resolve-data.spec.tsx, packages/core/lib/get-item.ts, packages/core/lib/resolve-all-props.ts, packages/core/lib/resolve-data.ts, packages/core/types/Config.tsx
This PR that introduces new APIs for expanding the capability of adaptors
* The `resolveProp` config API allows users to modify props dynamically without writing them to the Puck data model on a per-component basis.
* The `resolveData` util function allows users to apply their dynamic props on the server or client before rendering their page with the `<Render>` component
* The `mapProp` adaptor API to enable the user to return change the shape of the data returned by the adaptor before applying it as a prop
Additionally:
* It removes the `_data` API for adaptors in favour of `resolveProp`. This is a breaking change.
* It makes the types stricter for Fields (considered a Fix).
The Hero component in the demo app contains an example
```tsx
const config:Config = {
HeadingBlock: {
fields: { …
```
=> Introduce dynamic props via resolveProps API

packages/core/components/Heading/styles.module.css, packages/core/components/Puck/index.tsx
I slightly modified the style of the header area for #168
=> fix: puck header style for #168

packages/core/package.json
I believe this should be backwards compatible, but would be good to have tested by a few different node versions.
=> add explicit rsc and css exports

packages/core/components/Puck/index.tsx
Updating the `data` prop can confuse Puck, so we should freeze it into state
This use case would result in the `zones` being deleted on mount.
```tsx
const [puckData, setPuckData] = useState(data);
return (
<div>
<Puck
config={config}
data={puckData}
onChange={(updatedData) => {
setPuckData(updatedData);
}}
/>
</div>
);
}
```
=> fix: stop `zones` getting wiped out if data prop updated

README.md, packages/core/package.json, recipes/next/app/layout.tsx
#221 introduced explicit exports to allow the user to import the `rsc` and CSS bundles without reaching into `dist`.
However, this introduced this TypeScript issue: https://stackoverflow.com/questions/72193784/why-doesnt-the-exports-field-of-npm-work-in-typescript
Resolved using this answer: https://stackoverflow.com/a/73433177/1703260.
Testing via https://github.com/measuredco/measuredco-site/pull/118.
=> Fix TS module import error

apps/demo/config/blocks/Card/styles.module.css, apps/demo/config/blocks/Columns/index.tsx, apps/demo/config/blocks/Stats/styles.module.css, apps/demo/config/components/Header/index.tsx, apps/demo/config/components/Header/styles.module.css, apps/demo/config/components/Section/styles.module.css, apps/demo/config/root.tsx, packages/core/components/Button/Button.module.css, packages/core/components/ComponentList/index.tsx, packages/core/components/ComponentList/styles.module.css, packages/core/components/InputOrGroup/fields/ArrayField/styles.module.css, packages/core/components/InputOrGroup/styles.module.css, packages/core/components/LayerTree/index.tsx, packages/core/components/LayerTree/styles.module.css, packages/core/components/OutlineList/styles.module.css, packages/core/components/Puck/index.tsx, packages/core/components/Puck/styles.module.css, packages/core/components/SidebarSection/styles.module.css, packages/core/styles/typography.css, packages/plugin-heading-analyzer/src/HeadingAnalyzer.tsx
Closes #225 
First pass of responsive improvements
* Editor supports viewport widths down to `638px` without breaking
* Pragmatic widths for the editor page preview (helps alleviate some of the pain when editing responsive pages in a preview area narrower than the reported viewport width)
* Tightens up spacing in editor sidebars to maximise available space for longer names
* Ensures long strings can always be handled (defensive CSS)
* Prevents form zoom in iOS
* Adds some missing responsive behaviour to the demo app
For follow up work, suggest we make more granular issues, I can this handle as I go, for example
* Add a toggle for the right-hand sidebar
* Support viewports below `638px` wide
=> Improve responsive behaviour

packages/core/components/Puck/index.tsx
If the user has migrated to the new data API in [v0.11.0](https://github.com/measuredco/puck/releases/tag/v0.11.0), their root render method would not have received the props (although still accessible via the `state` prop).
=> fix: ensure updated root props are passed to root render

packages/core/components/Puck/index.tsx, recipes/next/database.json
The root data API in https://github.com/measuredco/puck/releases/tag/v0.11.0 moved props from `data.root` to `data.root.props`.
This change was implemented as a backwards compatible change. However, the backwards compatibility introduced  two bugs that resulted in the props being recursively spread.
=> Fix root resolver with new root data API

packages/core/components/Puck/styles.module.css
Having `overflow-x: auto` on a parent of the Droppable causes the following dnd warning whenever dragging an item:
> dnd.esm.js:31 @hello-pangea/dndDroppable: unsupported nested scroll container detected.A Droppable can only have one scroll parent (which can be itself)Nested scroll containers are currently not supported.We hope to support nested scroll containers soon: https://github.com/atlassian/react-beautiful-dnd/issues/131
See https://github.com/atlassian/react-beautiful-dnd/issues/131\#issuecomment-1634398431
Introduced in #225, which has not been released so using `chore`.
=> chore: stop dnd scoll container warning

CHANGELOG.md
This occured due to copy-and-paste formatting, and would not normally be an issue as this process is automated
=> docs: fix corrupt changelog

CHANGELOG.md, apps/demo/app/layout.tsx, apps/docs/pages/_document.tsx, turbo.json
Add two Plausible analytics scripts to the demo (demo.puckeditor.com) and docs site (puckeditor.com).
=> Add privacy-first analytics to docs

packages/core/components/InputOrGroup/fields/ArrayField/index.tsx
* Pass missing `ui` state to nested `onChange` method
* Lock drag to currently hovered array droppable
Closes #200
=> Fix broken nested array fields

apps/demo/config/blocks/Columns/index.tsx, apps/demo/config/index.tsx, apps/docs/pages/docs/api-reference/components/drop-zone.mdx, apps/docs/pages/docs/integrating-puck/categories.mdx, apps/docs/pages/docs/integrating-puck/multi-column-layouts.mdx, packages/core/components/DropZone/index.tsx, packages/core/components/Puck/index.tsx, packages/core/components/Render/index.tsx, packages/core/lib/resolve-all-data.ts
Introduces two new DropZone APIs:
* `allow` - only allow these components to be dropped in the DropZone
* `disallow` - allow all but these components to be dropped in the DropZone, unless it's specified by `allow`.
```tsx
import { DropZone } from "@measured/puck";
const config = {
components: {
Example: {
render: () => {
return (
<div>
<DropZone zone="my-content" allow={["HeadingBlock"]} />
</div>
);
},
},
},
};
```
These APIs be combined with categories:
```tsx
import { DropZone } from "@measured/puck";
const config = {
config: {
typography: {
components: ["HeadingBlock"],
},
},
components: {
Example: {
render: () => {
return (
<div>
<DropZone zone="my-content" allow={config.typography.components} />
</div>
);
},
},
},
};
```
Closes #103, closes #185
=> Add APIs to restrict components passed to a DropZone

apps/demo/config/blocks/Hero/index.tsx, apps/docs/pages/docs/api-reference/configuration/fields/external.mdx, apps/docs/pages/docs/integrating-puck/external-data-sources.mdx, packages/core/components/Button/Button.tsx, packages/core/components/ExternalInput/index.tsx, packages/core/components/ExternalInput/styles.module.css, packages/core/types/Config.tsx
This PR adds a search input to external fields with the new `showSearch` and `initialQuery` APIs added to the external field type.
https://github.com/measuredco/puck/assets/985961/53b6a864-b09d-4faa-a4cc-745b1f936d69
It is a partial implementation of #203. I chose to leave out pagination (due to complexity) and filtering (unclear how common a use-case this would be) for the time-being. We can track those in new tickets.
Closes #203
=> Add search to external fields

apps/demo/app/[...puckPath]/client.tsx, apps/demo/config/blocks/Hero/index.tsx, apps/demo/config/index.tsx, apps/docs/pages/docs/api-reference/configuration/fields.mdx, apps/docs/pages/docs/api-reference/configuration/fields/object.mdx, packages/core/components/InputOrGroup/fields/ObjectField/index.tsx, packages/core/components/InputOrGroup/fields/ObjectField/styles.module.css, packages/core/components/InputOrGroup/fields/RadioField/index.tsx, packages/core/components/InputOrGroup/index.tsx, packages/core/types/Config.tsx
This has come up numerous times (#60, #79, #226).
Whilst I still consider Fieldsets/Tabs (#64) and dot-notation (#142) good ways to solve for this, adding the `object` field type is much a lower effort way of supporting most of these use cases. These two APIs can also exist in parallel.
Closes #79.
=> Add object fields

packages/core/lib/__tests__/use-resolved-data.spec.tsx, packages/core/lib/use-resolved-data.ts
A race condition with the data resolvers meant that the UI state was being reset after the sidebars were collapsed. This is fixed by avoiding UI state updates on the initial resolveData call.
=> fix: fix initial UI state on mobile

apps/demo/app/custom-ui/[...puckPath]/client.tsx, apps/demo/config/blocks/Card/index.tsx, apps/demo/config/blocks/FeatureList/index.tsx, apps/demo/config/blocks/Stats/index.tsx, apps/demo/config/index.tsx, apps/demo/next.config.js, apps/demo/package.json, apps/docs/pages/docs/api-reference/components/field-label.mdx, packages/core/components/ComponentList/index.tsx, packages/core/components/DraggableComponent/index.tsx, packages/core/components/ExternalInput/index.tsx, packages/core/components/InputOrGroup/fields/ArrayField/index.tsx, packages/core/components/InputOrGroup/fields/DefaultField/index.tsx, packages/core/components/InputOrGroup/fields/ExternalField/index.tsx, packages/core/components/InputOrGroup/fields/ObjectField/index.tsx, packages/core/components/InputOrGroup/fields/RadioField/index.tsx, packages/core/components/InputOrGroup/fields/SelectField/index.tsx, packages/core/components/InputOrGroup/fields/TextareaField/index.tsx, packages/core/components/InputOrGroup/index.tsx, packages/core/components/LayerTree/index.tsx, packages/core/components/MenuBar/index.tsx, packages/core/components/Puck/index.tsx, packages/core/components/Puck/styles.module.css, packages/core/components/SidebarSection/index.tsx, packages/core/package.json, yarn.lock
https://lucide.dev
Actively maintained fork of _Feather_ icons, with a much improved selection of icons! (I am a major contributor).
https://lucide.dev/guide/packages/lucide-react
> Lucide is built with ES Modules, so it's completely tree-shakable.
=> Migrate to Lucide icons

apps/docs/components/Home/index.tsx, packages/core/components/Button/Button.tsx
The Next.js basePath was not getting applied as the `<Button>` component doesn't use Next's `<Link>` component.
=> docs: link to versioned docs on homepage "Read docs" CTA

apps/demo/config/blocks/Columns/index.tsx, apps/demo/config/blocks/Flex/index.tsx, apps/docs/pages/docs/api-reference/configuration/fields/number.mdx, apps/docs/pages/docs/integrating-puck/categories.mdx, packages/core/components/InputOrGroup/fields/DefaultField/index.tsx, packages/core/types/Config.tsx
Tiny PR to address #270
I wasn't sure if it started to make sense to pull the `NumberField` into its own component or add the 2 new props to the existing `DefaultField`. Went for the pragmatic approach. Happy to split it out as well if needed.
=> Add min and max properties to number field

packages/core/lib/__tests__/load-overrides.spec.tsx, packages/core/lib/load-overrides.ts, packages/plugin-heading-analyzer/README.md
React strict mode causes the Puck component to be rendered twice. The existing implementation treated the overrides as mutable, which resulted in plugins currying themselves on the second render. This would in turn cause a hydration error when server rendering as the resulting nodes differ between server and client.
=> Fix plugin currying

packages/core/types/Config.tsx
Allow both inline and read-only arrays for fields that take an `options` array (`select` and `radio` fields)
Currently, if you provide a readonly array (by specifying `as const` on the array), Puck will throw a TypeScript error.
```tsx
const selectOptions = [
{
label: "A",
value: "a",
},
{
label: "B",
value: "b",
},
] as const
export const SomeComponent: ComponentConfig<SomeComponentProps> = {
fields: {
selectField: {
type: "select",
options: selectOptions, // <-- This has a TS error
},
},
}
```
=> Fix file options types to allow readonly arrays

packages/plugin-heading-analyzer/package.json
the heading-analyzer plugin ```prepare``` and ```build```  often fails because of missing the tsup dev dependence in workspace
=> 🐛 FIX(heading-analyzer/building):  fix plugin build

apps/docs/pages/docs/api-reference/app-state.mdx
I found a broken link while browsing the docs.
=> Fix broken link in AppState API Reference

apps/docs/pages/docs/api-reference/overrides/component-item.mdx, apps/docs/pages/docs/api-reference/overrides/component-list.mdx, apps/docs/pages/docs/api-reference/overrides/fields.mdx, apps/docs/pages/docs/api-reference/overrides/header-actions.mdx, apps/docs/pages/docs/api-reference/overrides/header.mdx, apps/docs/pages/docs/api-reference/overrides/outline.mdx, apps/docs/pages/docs/api-reference/overrides/preview.mdx, apps/docs/pages/docs/api-reference/overrides/puck.mdx, packages/core/components/Drawer/index.tsx, packages/core/types/Overrides.ts
In an attempt to address #334, I discovered that the feature was actually not implemented.
This PR implements a `name` prop for the `componentItem` override.
Closes #334
=> Fix component item override

packages/core/types/Config.tsx
Adjusted the ObjectField type definition to ensure that properties present in Props are required and typed in the objectFields property. This resolves an issue where properties were not being inferred, leading to untyped fields.
Before:
After:
=> fix: Correct inference of objectFields in ObjectField type

packages/core/components/DragDropContext/index.tsx, packages/core/components/Draggable/index.tsx, packages/core/components/DraggableComponent/index.tsx, packages/core/components/Drawer/index.tsx, packages/core/components/DropZone/index.tsx, packages/core/components/Droppable/index.tsx, packages/core/components/InputOrGroup/fields/ArrayField/index.tsx, packages/core/components/Puck/context.tsx, packages/core/components/Puck/index.tsx
New iframe / viewport features don't play well with server rendering, such as Next.js static builds. This change defers the rendering of dnd behaviour until the client is ready.
=> refactor: don't load dnd until client is ready

packages/core/package.json, packages/plugin-heading-analyzer/package.json, packages/tsup-config/index.ts, packages/tsup-config/package.json, yarn.lock
tsup now processes css pre-processes natively
this is also resolves core yarn build --watch not refreshing css changes
see https://github.com/egoist/tsup/issues/536#issuecomment-1752121594
=> fix: tsup watch mode not refreshing on css change

packages/core/components/ExternalInput/index.tsx, packages/core/components/InputOrGroup/fields/ArrayField/index.tsx
Closes #345
ExternalInput and ArrayFields have button elements which assumed the default type "submit". This causes the buttons to be automatically triggered when "Enter" keypress happens on other inputs of the form.
Setting their type as "button" instead, fixes the behaviour.
=> fix: "Enter" keypress when using ExternalInput together with ArrayFields

packages/core/components/Button/Button.module.css
On dark color modes, the secondary Button is currently rendering with dark borders and text, resulting in poor contrast.
Using currentColor addresses this, especially since the main Puck editor does not yet have a dark mode, but the docs do.
Note, this bug is not yet released so a `chore` is the suitable commit type.
=> chore: fix Button color on dark mode

packages/core/components/DraggableComponent/index.tsx, packages/core/lib/is-ios.ts, packages/core/package.json, yarn.lock
Disabling animations prevents a "Safari encountered a problem" error when dragging an item on a desktop viewport on iOS Safari, which was likely due to a GPU memory issue.
=> chore: prevent iOS crashes when dragging in large viewport

apps/demo/tsconfig.json, packages/core/components/Puck/index.tsx, packages/core/components/Puck/styles.module.css, packages/core/package.json, packages/core/types/Config.tsx, packages/plugin-heading-analyzer/package.json, packages/plugin-heading-analyzer/src/HeadingAnalyzer.tsx, packages/tsup-config/index.ts, packages/tsup-config/package.json, yarn.lock
A few final fixes before `v0.14.0` release based on canary testing.
@4leite I had to revert #359 as the esbuild implementation of CSS modules does not isolate styles using a random hash, only by checking for conflicts with the rest of the bundle. Since we don't know the final bundling environment, we require a random hash to avoid collisions.
i.e. instead of names like `.Button-abc123`, tsup (aka esbuild) is generating names like `.Button`. Perhaps there is a way to address this, but I couldn't see anything when reading [the docs](https://esbuild.github.io/content-types/#local-css), and didn't want to delay the release to debug fully.
=> Pre release fixes

CHANGELOG.md, apps/docs/package.json, apps/docs/pages/docs/api-reference/configuration/component-config.mdx, apps/docs/pages/docs/api-reference/fields/number.mdx, apps/docs/pages/docs/api-reference/overrides/component-item.mdx, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/field-contentful/package.json, packages/plugin-heading-analyzer/package.json
Puck v0.14.0 introduces the long awaited viewport switching feature, with drag-and-drop-friendly iframe rendering for full CSS media query support.
1. [**Viewport switching**](https://puckeditor.com/docs/integrating-puck/viewports): Render your entire Puck preview inside an iframe for full CSS media query support. Override the viewports using the `viewports` API.
2. [**New field APIs**](https://puckeditor.com/docs/api-reference/fields): Array and number fields now accept `min`/`max` params, and external fields can now render search filters using the familiar `fields` API.
3. [**New component label API**](https://puckeditor.com/docs/api-reference/configuration/component-config#fields): Provide a custom label to use as your component name.
4. [**Contentful field …
=> release: v0.14.0

packages/core/components/ViewportControls/index.tsx
Some users were reporting the following error when zooming their browser (not Puck's internal zoom) quickly:
> TypeError: Cannot read properties of undefined (reading 'value') at ViewportControls
Unable to reproduce, but this might help.
=> refactor: make ViewportControl zoom more robust

packages/core/package.json, yarn.lock
If additional iframes were present in the host window, @measured/dnd was attempting to scan them for draggable elements. If the iframe was on a different origin, this would throw a security warning.
Fix here: https://github.com/measuredco/dnd/commit/4b9daa14243c8ce929c4e61b5119791661a2f82c
Might close #407
=> fix: resolve security warning when additional iframes present

packages/core/components/Puck/components/Canvas/index.tsx
#412 identified an issue that resulted in the preview width collapsing down to the width of the contents when iframes are disabled. If there is no contents, the preview would not be visible.
This fixes it by setting the width to 100%, as expected.
Closes #412
=> fix: use 100% width for Puck frame when iframe disabled

packages/core/package.json, yarn.lock
Users are experiencing a new issue as part of #407.
> Cannot read properties of null (reading 'document')
Struggling to reproduce, so I'm attempting to fix by checking if the iframe document exists before querying.
Fix here: https://github.com/measuredco/dnd/commit/9296074431dce92cd3599ed91a46e1d1c28d5a26
=> fix: don't query iframe document if not ready

packages/core/package.json, yarn.lock
After #415, users in #407 observed that the iframe took a long time to load. This attempts to fix that by refactoring the event binding watchers to attempt bind the contentWindow when it becomes available, as seen here: https://github.com/measuredco/dnd/commit/f4721351bee5d4cc797c7b07fc99bf727e1b2500
=> fix: defer iframe event binding until contentWindow is ready

packages/core/components/InputOrGroup/fields/SelectField/index.tsx
When using a boolean value with the select field, the value always evaluates to true (a similar implementation works as expected with the radio field).
https://codesandbox.io/p/sandbox/sleepy-fast-x7cdwn
[Working Radio field code.](https://github.com/measuredco/puck/blob/main/packages/core/components/InputOrGroup/fields/RadioField/index.tsx#L40-L46)
=> fix: Fix support for boolean values with select field.

packages/core/components/DropZone/index.tsx, packages/core/components/Puck/context.tsx, packages/core/package.json, yarn.lock
Safari 17.2 introduced a bug that's not being fixed until [17.5](https://developer.apple.com/documentation/safari-release-notes/safari-17_5-release-notes), which is still in beta:
> Fixed mousemove events in an iframe when the mouse is clicked from outside the iframe and then moves into it while the button is held down. (120540148) (FB13517196)
This impacts the new Puck 0.14 release when using iframes (the default behaviour).
Add a warning and activate compatibility mode when a user is using Safari 17.2, 17.3 or 17.4.
~The compatibility mode is not perfect, and results in some unexpected behaviour when using DropZones. One example of this is that the first column in the Columns component in the demo application will not accept a new component - only one from another column. The other …
=> fix: add DropZone iframe compatablity mode for bug in Safari 17.2, 17.3 and 17.4

packages/core/package.json, yarn.lock
This may occur in dev environments when styles are injected into the parent <head>, causing issues if this occurs during a drop. For example, using @mui/material in form inputs injects styles as soon as an item is dropped via emotion, causing the main thread to hang. Deferring this until after the main thread is completed via measured/auto-frame-component@0.1.3 [addresses the issue](https://github.com/measuredco/auto-frame-component/commit/f62f5e83d896557734306830344303bfd84aad95).
May address the final issues observed in https://github.com/measuredco/puck/issues/407#issuecomment-2049121046.
=> perf: don't lock main thread when iframe styles changed

packages/core/package.json, yarn.lock
Batch load styles into the initial iframe load, which drastically increases performance when numerous <style> attributes exist. This is often the case when using solutions like emotion in development environments.
Refactor: https://github.com/measuredco/auto-frame-component/commit/0bb7efce9996a1f1a2fd110ded94fed0a3f88ecd
May resolve final #407 issues.
=> perf: batch load initial iframe styles

packages/core/components/InputOrGroup/fields/RadioField/index.tsx
When a prop change is made in `resolveData`, that value is not reflected when using a radio field but reflected in the render of the component.
In this example, when a change is made to `children` the expected behaviour is that the `align` prop reverts to `"center"`.
Notice that even though the text is aligned in the centre and the prop value has changed, the radio button shows either "left" or "right" as the selected value.
[Bug reproduction ](https://codesandbox.io/p/sandbox/elastic-sutherland-x963k4).
Example with this PR's code change.
=> fix: Reflect value changes made in resolveData in radio field.

packages/core/package.json, yarn.lock
auto-frame-component was not handling some `<link>` tags correctly, and attempting to load them twice when preload links were present.
Fix: https://github.com/measuredco/auto-frame-component/commit/d298f1b36ed31611604ad4a9f3e5f91da61ba775
Prevent duplicate loading: https://github.com/measuredco/auto-frame-component/commit/ad6452fdac880b3dc202aeab006d48ab8328e0e7
Addresses another issue in #407
=> chore: load iframe consistently

apps/docs/pages/docs/api-reference/components/puck.mdx, packages/core/components/Puck/index.tsx, packages/core/types/IframeConfig.tsx
Adds an API to disable auto-scroll if necessary.
Some payloads may result in choppy scrolling. This is hard to patch without rebuilding the dnd library (which is in progress). Providing an opt-out allows users to disable it if necessary in the mean-time, and will still be a valid option in the future.
Flagged this as a `perf` instead of `feat` as it's necessary to stabilise the 0.14 release.
=> perf: add API for disabling auto-scroll due to performance issues

packages/core/package.json, yarn.lock
Closes #441, which was caused by auto-frame-component replacing the `onload` handler, which tinymce relies on. Fixed by replacing this with an event listener: https://github.com/measuredco/auto-frame-component/commit/c8e1b61caa22b445a88688bd0f5ec1833280e505
Closes #441
=> chore: don't replace onload handler on existing style tags

apps/demo/tsconfig/nextjs.json, apps/docs/tsconfig/nextjs.json, packages/core/components/AutoFrame/index.tsx, packages/core/components/Puck/components/Preview/index.tsx, packages/core/package.json, yarn.lock
Inlining link stylesheets has unexpected side effects as browsers serialize the styles. This can cause styles to become invalid in certain circumstanecs, such as those outline in https://github.com/measuredco/puck/issues/454.
This fix removes inlining of link styles, which may come at a performance cost. However, inlining was implemented before further performance optimisations were made, so the impact may be negliable. We should publish a canary to assess the impact.
09ca807b006c74a93325e3a7cad1b6cd60c45fba is the commit containing the changes. The initial commit just brings the auto-frame-component inline into the Puck repo, as it awkward to continuously iterate it externally.
Closes #454
=> Dont inline iframe styles

apps/demo/app/[...puckPath]/client.tsx, apps/docs/pages/docs/api-reference/overrides/header-actions.mdx, apps/docs/pages/docs/extending-puck/custom-interfaces.mdx, packages/core/components/MenuBar/index.tsx, packages/core/components/Puck/index.tsx, packages/core/types/Overrides.ts
Move the publish button to `children` of the `headerActions` override to enable the user to override the publish header.
Closes #378.
This is a breaking change: `headerActions` overrides must now render `children` to render the publish button.
=> feat: enable override of publish button (breaking change)

README.md, apps/docs/pages/docs/api-reference/components/puck.mdx, apps/docs/pages/docs/api-reference/components/render.mdx, apps/docs/pages/docs/api-reference/functions/resolve-all-data.mdx, apps/docs/pages/docs/api-reference/functions/transform-props.mdx, apps/docs/pages/docs/getting-started.mdx, packages/core/components/Puck/index.tsx, packages/core/components/Render/index.tsx, packages/core/lib/default-data.ts, packages/core/lib/resolve-all-data.ts, packages/core/lib/transform-props.ts
This is a long-standing API tidy-up to enable partial Data objects to be provided to Puck for easier instantiation.
=> feat: allow data prop to accept an empty object

apps/demo/config/blocks/Hero/index.tsx, apps/docs/pages/docs/api-reference/configuration/component-config.mdx, apps/docs/pages/docs/index.mdx, apps/docs/pages/docs/integrating-puck/_meta.json, apps/docs/pages/docs/integrating-puck/dynamic-fields.mdx, packages/core/components/Puck/components/Fields/index.tsx, packages/core/components/Puck/components/Fields/styles.module.css, packages/core/lib/get-changed.ts, packages/core/lib/resolve-component-data.ts, packages/core/lib/resolve-root-data.ts, packages/core/types/Config.tsx
Introduces the new `resolveFields` API for setting fields dynamically.
```ts
resolveFields: async (data, { fields }) => {
if (data.props.align === "center") {
return {
...fields,
image: undefined,
};
}
return fields;
},
```
This is accessible on:
* The `root`
* A component config
* An `external` field
Bonus: Adds additional `lastData` parameter to existing `resolveData` function, for consistency with new `resolveFields` API.
---
Closes #280, closes #188
=> Support dynamic fields

packages/core/components/MenuBar/index.tsx
Use undo/redo icons rather than chevrons for moving back/forth in history.
=> Replace chevrons with undo/redo icons

.github/workflows/ci.yml, CHANGELOG.md, apps/docs/package.json, apps/docs/pages/docs/api-reference/fields/custom.mdx, apps/docs/pages/docs/integrating-puck/dynamic-fields.mdx, lerna.json, package.json, packages/core/components/Puck/components/Fields/styles.module.css, packages/core/package.json, packages/core/types/Fields.ts, packages/create-puck-app/package.json, packages/field-contentful/index.ts, packages/field-contentful/package.json, packages/plugin-heading-analyzer/package.json
Puck v0.15.0 introduces a powerful new API for dynamically defining fields, and exports Puck's internal field component for use within custom fields.
1. [**Dynamic fields**](https://puckeditor.com/docs/integrating-puck/dynamic-fields): Use the `resolveFields` API to dynamically build your fields object whenever the props change.
2. [**AutoField component**](https://puckeditor.com/docs/api-reference/components/auto-field): Puck's internal field component is now exported, for use within your own custom fields.
3. [**Override Publish button**](https://puckeditor.com/docs/api-reference/overrides/header-actions): Swap out the publish button without swapping out the entire header.
4. [**New `puck.isEditing` prop**](https://puckeditor.com/docs/api-reference/configuration/component-config#puckised …
=> release: v0.15.0

packages/plugin-heading-analyzer/src/HeadingAnalyzer.module.css, packages/plugin-heading-analyzer/src/HeadingAnalyzer.tsx
Refactor heading analyzer to use CSS modules instead of inline styles, and show a warning if the user doesn't have the CSS styles loaded.
=> Refactor heading outline styles

apps/docs/pages/docs/api-reference/app-state.mdx, apps/docs/pages/docs/api-reference/components/puck.mdx, apps/docs/pages/docs/api-reference/functions/use-puck.mdx, packages/core/components/Puck/index.tsx, packages/core/lib/use-history-store.ts, packages/core/lib/use-puck.ts
Streamline history APIs and docs, including:
1. Exposing more useful props under the `usePuck` history API, so the user doesn't need to reach into `history.historyStore`
2. Documenting the `usePuck` history API, which should have been done when the feature was implemented
3. Renaming the new `initialHistories` API to `initialHistory` to match the usePuck history API
4. Make references from the new `initialHistory` API to the usePuck `histories` API
Tagging @mkilpatrick for review since you implemented `initialHistories` in #505.
=> Streamline history APIs and docs

apps/docs/pages/docs/api-reference/functions/use-puck.mdx, packages/core/index.ts, packages/core/lib/__tests__/use-history-store.spec.tsx, packages/core/lib/__tests__/use-puck-history.spec.tsx, packages/core/lib/use-history-store.ts, packages/core/lib/use-puck-history.ts, packages/core/lib/use-puck.ts
This addresses https://github.com/measuredco/puck/issues/519.
This change exposes the history store's setHistories and setHistoryIndex functions. When they are called the data is dispatched so that Puck rerenders. The use case this supports is when a Puck consumer wants to change or reset the history state manually without requiring the page to be refreshed.
=> feat: expose setHistories and setHistoryIndex

packages/core/types/Fields.ts
I narrowed the TypeScript errors to this PR #368
Because the ObjectField is `any` objectFields _could_ be an array here:
[SubPropName in keyof Props]: Field<Props[SubPropName]>;
I've added a check so that it can only be an object which gets rid of the the Config mismatch errors and keeps typing within the objectFields
=> Help out the generics by ensuring that objectFields is never an array.

apps/docs/pages/docs/api-reference/components/puck.mdx, packages/core/components/Puck/index.tsx, packages/core/reducer/index.ts, packages/core/types/OnAction.ts
Addresses https://github.com/measuredco/puck/issues/534
This change adds an `onAction` callback to the Puck editor. When an action occurs in the editor, this callback is called with the `action`, `appState`, and `prevAppState`. Enables tracking changes, performing side effects, or syncing with external systems.
=> Add on action prop

packages/core/components/MenuBar/index.tsx
Removing the stroke from the Lucide icon as the fill can be inherited by the parent icon button CSS. 
Fixes #330
=> Removing the stroke from the Lucide icon

apps/demo/app/custom-ui/[...puckPath]/client.tsx, packages/core/components/ActionBar/styles.module.css, packages/core/components/ComponentList/index.tsx, packages/core/components/DragIcon/index.tsx, packages/core/components/DragIcon/styles.module.css, packages/core/components/Draggable/index.tsx, packages/core/components/DraggableComponent/index.tsx, packages/core/components/Drawer/index.tsx, packages/core/components/Drawer/styles.module.css, packages/core/components/DropZone/index.tsx, packages/core/components/Puck/components/Fields/index.tsx, packages/core/components/Puck/index.tsx, packages/core/lib/get-permissions.ts, packages/core/lib/use-puck.ts, packages/core/types/Config.tsx
=> feat: adding permissions to core actions and disabling on Hero

apps/demo/app/custom-ui/[...puckPath]/client.tsx, packages/core/components/ActionBar/index.tsx, packages/core/components/ComponentList/index.tsx, packages/core/components/ExternalInput/index.tsx, packages/core/components/LayerTree/index.tsx, packages/core/components/SidebarSection/index.tsx
If use PUCK inside &#60;Form /&#62;, &#60;button/&#62; without type="button" submits the form
=> Added type for button

packages/core/components/Puck/components/Canvas/index.tsx, packages/core/components/Puck/components/Canvas/styles.module.css
If loading takes over 500ms, show a spinner before rendering the iframe.
=> Add iframe spinner during slow loads

recipes/next/app/puck/[...puckPath]/page.tsx, recipes/next/app/puck/page.tsx
Next.js cache was interfering with the dynamic `/puck` route in the next recipe. Note, the regular route is behaving as expected.
This fix forces the /edit route to use dynamic rendering.
1. Clone the repo
2. Run yarn to install dependencies
3. Run yarn build to generate a build
4. Run yarn start to run the production build
5. Navigate to page editor
6. Reload the page
7. Make changes and hit the publish button
8. Reload the page 
The old data was shown
The new data to be shown
=> fix: don't cache /edit route in Next recipe

apps/docs/pages/docs/integrating-puck/dynamic-props.mdx, packages/core/lib/__tests__/insert-component.spec.tsx, packages/core/lib/insert-component.ts
This will result in duplicate history entries if the item has a resolveData method. This is difficult to prevent without a deferredDispatch method, similar to that being explored in #598.
=> fix: always record history on component insert

apps/docs/pages/docs/api-reference/components/puck.mdx, apps/docs/pages/docs/api-reference/functions/use-puck.mdx, packages/core/components/Puck/components/Canvas/index.tsx, packages/core/components/Puck/index.tsx, packages/core/index.ts, packages/core/lib/__tests__/use-history-store.spec.tsx, packages/core/lib/__tests__/use-puck-history.spec.tsx, packages/core/lib/flush-zones.ts, packages/core/lib/use-history-store.ts, packages/core/lib/use-puck-history.ts, packages/core/types/API/index.ts
Rework the history store to ensure intialHistories API works as expected. Previously, the historyStore would assume that `data` was the first item in history, and all history was additive. This PR reverses the logic, placing `data` at the end of the history to enable injection of custom histories.
Changes:
* Make `initialHistories` mandatory internally when using the `useHistoryStore` hook 
* Set `EMPTY_HISTORY_INDEX` to `0` instead of `-1`, since some history always exists
* Set the last history item to the `data` prop
* Remove unnecessary `id` parameter in `History` type
* Fix an issue preventing viewports from resizing when changed programatically (encountered when testing history)
Default history store:
```ts
[]
```
Injecting history via `initialHistories` prop API
```ts
[
{
data: {} …
```
=> Rework history store

CHANGELOG.md, apps/demo/app/[...puckPath]/client.tsx, apps/demo/lib/use-demo-data.ts, apps/docs/package.json, apps/docs/pages/docs/api-reference/components/puck.mdx, apps/docs/pages/docs/api-reference/functions/use-puck.mdx, apps/docs/pages/docs/integrating-puck/feature-toggling.mdx, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/field-contentful/package.json, packages/plugin-emotion-cache/package.json, packages/plugin-heading-analyzer/package.json
We're celebrating 5,000 stars on GitHub! Thank you to our wonderful community! :star_struck:
[Puck v0.16](https://github.com/measuredco/puck/releases) is a big release, introducing the headline permissions API and — you guessed it — quality of life improvements. This one took a while to put together, and we appreciate your patience and support :pray:
[Permissions](https://puckeditor.com/docs/api-reference/permissions) enable you to [toggle core Puck functionality](https://puckeditor.com/docs/integrating-puck/feature-toggling) globally, on a per-component basis or dynamically.
```tsx
export function Editor() {
return (
<Puck
permissions={{
delete: false,
duplicate: true
}}
/>
);
}
```
The new [`actionBar` override](https://puckeditor.com/docs/api-reference/overrides/action-bar) enables you …
=> Prep release

packages/core/components/ActionBar/styles.module.css
fixs little visual bug where the actions's left border of the default action bar would look weird in RTL mode
set the `direction` of the iframe's html element (or the root html if you disabled iframe) to `rtl` and select any of the components in the preview
=> fix:defaultActionBar actions left border in RTL mode

packages/core/lib/use-resolved-permissions.ts
=> fix: don't crash if component definition missing

apps/demo/config/blocks/Hero/index.tsx, packages/core/components/ExternalInput/index.tsx, packages/core/types/Fields.ts
- Adds support for `mapRow` items of type `ReactElement` (previously just `string | number`)
- Resolves #506 
```
mapRow: (item) => ({
img: (
),
title: item.title,
description: item.description,
}),
```
=> feat: allow react elements in external field mapRow

apps/demo/config/blocks/Hero/index.tsx, apps/docs/pages/docs/api-reference/fields/external.mdx, packages/core/components/ExternalInput/index.tsx, packages/core/components/ExternalInput/styles.module.css, packages/core/types/Fields.ts
Adds a new optional property to external fields, `renderFooter`. This property accepts a function resolving to a `ReactElement` in place of the default footer, with a prop provided for `items` representing the `mappedData`. 
We're using the `external` field to allow the user to select an image from a set of images provided by our external service. We'd like to be able to display a "Manage Images" link in the footer to provide the user with a clear path to add/remove any of the image options displayed in the modal.
=> feat: add renderFooter option in external field

packages/core/components/AutoField/fields/ArrayField/index.tsx
First of all, thanks for such awesome library.
For some purposes it's useful to have duplicate functionality not only for the whole component but also for Array field element itself.
=> feat: array field element duplicate functionality

apps/demo/config/blocks/Columns/index.tsx, apps/demo/config/index.tsx, apps/docs/pages/docs/api-reference/app-state.mdx, packages/core/components/AutoField/fields/ArrayField/index.tsx, packages/core/components/AutoField/index.tsx, packages/core/components/AutoField/styles.module.css, packages/core/components/Puck/context.tsx, packages/core/lib/__tests__/use-resolved-data.spec.tsx, packages/core/types/AppState.tsx
61260407c5c87cc8c5c4fe925835f2d0d2a6f9ff resulted in an issue when running resolveData, as the field would not re-render after a quick resolveData run.
A timeout was always a poor solution for this issue, so this PR tracks the currently focused field on the app state, and replaces the timeout with a condition that the current field cannot be focused to be updated externally.
This PR also improves the columns demo by generating IDs dynamically, so they can actually be reordered. Attempting to implement this docs improvement is what exposed the underlying issue.
=> Always update fields when resolveData runs

apps/docs/pages/docs/api-reference/permissions.mdx
Noticed that the word "duplication" had duplicated itself.
=> Fix wording of delete permission documentation

packages/core/components/AutoField/fields/DefaultField/index.tsx, packages/core/components/AutoField/fields/RadioField/index.tsx, packages/core/components/AutoField/fields/SelectField/index.tsx, packages/core/lib/safe-json-parse.ts
https://github.com/measuredco/puck/issues/713
- Aims to fix For when select boxes that have number values  this PR adds a check and JSON.parse the value.
- (also sneakily adds a title attr for added accessibility)
An alternative approach might be to safely JSON parse all values and should that fail just return the value as is or an empty string. https://gist.github.com/jswhisperer/ec7c99dab7ca8549f40cbd1e853399ae
=> fix: adds condition check for number values in select

packages/core/components/AutoField/index.tsx
Because the radio button implementation uses a sibling `div` element, the click event was bubbling up to the `array` parent, where `preventDefault` would be called before the event could change the `input`.
The `preventDefault` is necessary to prevent arrays from misbehaving when used inside a `label` element, which would cause one of the array actions (delete/duplicate) to trigger when the array item summary was clicked.
The bubbling here is slightly confusing, because of the sibling nature of the radio field.
Fix is to stop propagation of the event. This could be done on the sibling `div` element, but better in the `AutoField` component to prevent the same bug from impacting custom field implementations.
Closes #723
=> Fix radio buttons in arrays

CHANGELOG.md, apps/docs/package.json, apps/docs/pages/docs/api-reference/fields/external.mdx, apps/docs/releases.json, apps/docs/theme.config.tsx, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/field-contentful/package.json, packages/plugin-emotion-cache/package.json, packages/plugin-heading-analyzer/package.json, recipes/next/README.md
Bugs noticed during prep:
Puck v0.17.0 introduces adds support for React 19, improves various field APIs and squashes some bugs.
_This is our final feature release of the year! We're delaying the [new drag-and-drop engine](https://github.com/measuredco/puck/pull/598) release until January while we iron out the last few kinks. Happy holidays, and thanks for being a wonderful community 🎄_ 
- **React 19 support**: We've made [React 19](https://react.dev/blog/2024/12/05/react-19) support official by adding it to the supported list of peer dependencies.
- **Next.js 15**: Upgraded the next recipe to use [Next 15.1](https://nextjs.org/blog/next-15) and React 19 by default.
- **[New external field APIs](https://puckeditor.com/docs/api-reference/fields/external)**: External fields now support …
=> release: v0.17.0

packages/core/components/AutoField/fields/RadioField/index.tsx, packages/core/components/AutoField/fields/SelectField/index.tsx
`safeJsonParse(false)` returns `false` so `const jsonValue` will be `"false"` and cannot be found in `flatOptions`.
We need to check for `undefined` and not for `false`.
=> fix: booleans type in select/radio fields

packages/plugin-emotion-cache/index.tsx
See [Discord thread](https://discord.com/channels/1153376562259951687/1322960022757445672/1323240307533287445). Using the emotion cache plugin with `initialData` was preventing styles from loading. Adding a timeout of 0ms addresses it.
=> fix: fix plugin-emotion-cache style sync when using initialData

packages/core/lib/dnd/NestedDroppablePlugin.ts, packages/core/lib/global-position.ts
The handleMove overEl check did not account for the iframe scale, making the plugin unresponsive near the perimeter of the frame.
Bug introduced in #767
=> refactor: account for iframe transform when triggering nested plugin

packages/core/components/Puck/components/Fields/index.tsx
Parent does not exist on first render, but the resolver would only run on first render.
This defers rendering of the resolver until after the parent exists, unless the item is not inside another element.
Closes #777
=> fix: ensure parent is not null on first render in resolveFields

packages/core/components/DropZone/index.tsx
This is in relation to Issue #778 and PR #790 
Whilst #790 solved the issue for renderDropZone in the puck editor. The same issue was still in the RSC render function.
This seems to fix that, I've tested on both a RSC implementation and the puck demo app.
=> SSR issues still on render with new dnd engine

packages/core/lib/dnd/PointerSensor.ts
The pointerup event handler was preventing propagation, even if the user was not currently dragging.
Fixed by adding a check to the sensor. Also moving fix upstream to https://github.com/clauderic/dnd-kit/pull/1566.
Closes #769
=> refactor: don't prevent pointerup propagation when no drag

packages/core/components/DropZone/index.tsx
Follow on from #778, which is causing the `renderDropZone` function to be redefined on each render, resulting in flashing in the docs (and possible performance issues otherwise).
https://github.com/user-attachments/assets/ff14c1df-6488-4a21-b6b7-ed41b6260892
=> refactor: prevent renderDropZone from being redefined on each render

packages/core/components/DropZone/index.tsx
When dropping in a new component, the "No configuration for preview" would appear momentarily, before the component is rendered. This is due to a race condition introduced in #767, as the preview is kept in Zustand, which triggers a render before the data updates (which kept in context).
Might be able to refactor this once all state moves to zustand as part of #644.
=> refactor: handle case where preview state updates before data

apps/docs/pages/docs/api-reference/components/puck-fields.mdx, packages/core/components/AutoField/styles.module.css, packages/core/components/Puck/components/Fields/index.tsx, packages/core/components/Puck/components/Fields/styles.module.css
When trying to solve [this issue](https://discord.com/channels/1153376562259951687/1328683387514261504/1329067870931652688) using existing field overrides and APIs, I noticed that it was impossible to achieve the desired styles due to an implementation of padding and border on FieldLabel.
Having these styles on FieldLabel has caused issues before (see #666).
This PR moves these wrapping styles to `<Puck.Fields>`, which can now be toggled via the `wrapFields` prop in custom interfaces.  This is the correct place to define these styles, as the wrapping should only ever occur when used within the default `<Puck.Fields>` component.
=> Fix remaining field label issues

apps/demo/config/components/Layout/index.tsx, packages/core/components/Puck/components/Fields/index.tsx
`lastFields` was not clearing inside nested components when selecting a new component.
This bug was introduced in 37cfc43156e75f20f91899660a9a9bfa1dd2bc23 (and equivalent in 0.17.2).
=> Reset lastFields on component change

apps/demo/config/root.tsx, packages/core/styles.css
This was originally implemented in 3d93f46 as part of this release, but the implementation was incomplete.
=> Ensure root DropZone fills container

packages/core/components/AutoField/fields/DefaultField/index.tsx, packages/core/lib/__tests__/use-resolved-permissions.spec.tsx, packages/core/lib/use-resolved-permissions.ts
Puck was handling `undefined` but not `null` in the DefaultField. This adds stricter typing (which would have caught it), and addresses the underlying issue.
Also does some unrelated tidy up.
Will be released in 0.17.4 (e778246). This implementation if for 0.18.
Closes #775
=> refactor: handle null when provided to text/textarea/number fields

packages/core/components/DragDropContext/index.tsx, packages/core/components/DraggableComponent/index.tsx, packages/core/components/DropZone/context.tsx
Addresses issues where selecting an item nested within a component that has not yet been selected does not receive the path.
This only affects 0.18. Moving to a slot API (via #255) should eliminate zone flushing and registering, as the zone data will be statically deterministic, rather than only known at runtime.
1. Go to https://demo.puckeditor.com/debug/edit
2. Drag in a flex component
3. Nest another flex component inside the first one
4. Drag in a heading inside the flex component
5. Publish the page
6. Refresh
7. Immediately select the heading component, without selecting anything else
No "Flex" breadcrumb is not visible in the top right, with only the "Heading" title shown, indicating the path data is not known. Equally, the fields are not resolved (see both grid and flex fields …
=> Address issue with pathData not resolving

packages/core/components/DropZone/index.tsx
This was a bug introduced when optimising performance and adding the render debug mode.
=> refactor: don't wipe out style.backgroundColor on DropZone

packages/core/components/DraggableComponent/styles.css
Previous commit addressed a bug related to the data- attributes being overwritten when using `dragRef` with a DropZone, but failed to address the underlying CSS styles that enable the DropZone to capture the necessary pointer events to trigger the NestedDroppablePlugin.
=> refactor: ensure DropZones can still capture pointer event

CHANGELOG.md, apps/docs/package.json, apps/docs/releases.json, apps/docs/theme.config.tsx, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/field-contentful/package.json, packages/plugin-emotion-cache/package.json, packages/plugin-heading-analyzer/package.json
Puck 0.18 launches our groundbreaking drag-and-drop engine for page building with advanced CSS layouts.
With native support for CSS grid and flexbox, Puck 0.18 enables powerful new paradigms for creating design-in-browser experiences directly within your Puck application.
Thanks to our contributors and sponsors for making this huge milestone possible.
https://github.com/user-attachments/assets/8269b081-7fce-479d-92e9-1e9dce4bae29
- **New drag-and-drop engine**: Multi-dimensional drag-and-drop across any CSS layout to create a sophisticated page building experience. [Read the docs](https://puckeditor.com/docs/integrating-puck/multi-column-layouts).
- **Dynamic DropZone height**: DropZones now shrink to the height of their children, with a [configurable …
=> release: v0.18.0

packages/core/components/Puck/components/Preview/index.tsx
Nested components in 0.18 aren't working in Firefox.
=> fix: ensure nested drag-and-drop works in Firefox

packages/core/package.json, yarn.lock
1. ~Include dnd-kit as part of bundle, as I _believe_ this was originally excluded due to a lack of source maps, which were added in https://github.com/clauderic/dnd-kit/pull/1567.~ Results in "AutoScroller plugin depends on Scroller plugin"
2. Upgrade to latest dnd-kit, once the necessary peer-dependencies are added (https://github.com/clauderic/dnd-kit/pull/1590) (update: merged, waiting on nightly release)
Closes #826
=> fix: address React 19 peer dependency issues

CHANGELOG.md, apps/docs/package.json, lerna.json, package.json, packages/core/package.json, packages/create-puck-app/package.json, packages/field-contentful/package.json, packages/plugin-emotion-cache/package.json, packages/plugin-heading-analyzer/package.json
* address React 19 peer dependency issues ([7649086](https://github.com/measuredco/puck/commit/7649086009deb9b9ceb5c4790e9c356b107a20b6))
* address ResizeObserver loop error ([d3e6b57](https://github.com/measuredco/puck/commit/d3e6b57190e3f6e8a4f857a45a51cbb060daf050))
* don't access selectedItem if undefined right after drop ([0573b18](https://github.com/measuredco/puck/commit/0573b182452f1c614a15f4125fefa81a880e37a2))
* ensure nested drag-and-drop works in Firefox ([f077a37](https://github.com/measuredco/puck/commit/f077a37158194867a10c1406252fe4a8f4f6974c))
=> release: v0.18.1

apps/docs/pages/docs/api-reference/app-state.mdx, packages/core/lib/use-preview-mode-hotkeys.ts
@FedericoBonel would you mind testing this now I've added an explicit hotkey? If this doesn't work, we can try a new binding.
Closes #851
=> fix: ensure ctrl+i interactive toggle hotkey works on Windows

packages/core/lib/__tests__/use-resolved-fields.spec.tsx, packages/core/lib/use-resolved-fields.ts
The [resolveFields refactor](#808) and test coverage missed a critical feature: providing the updated props to the `resolveFields` method.
Closes #850
=> Provide updated props to resolveFields

apps/demo/config/blocks/Hero/index.tsx, packages/core/components/AutoField/fields/ArrayField/index.tsx, packages/core/components/AutoField/fields/ArrayField/styles.module.css, packages/core/components/DragDropContext/index.tsx, packages/core/components/ExternalInput/index.tsx, packages/core/components/ExternalInput/styles.module.css, packages/core/components/Sortable/index.tsx, packages/core/lib/dnd/use-sensors.ts
Closes #858, and other changes.
=> Address dnd issues in array fields

packages/core/components/DragDropContext/index.tsx
Some lifecycle tidy up was missed as part of the DropZone performance improvements (#795) and subsequent bug fixes (#814), resulting in cancelled drags not removing the preview item.
Closes #863.
=> fix: tidy up stale items during fast drags or cancellation

packages/core/types/API/Overrides.ts
This fixes #626.  Although the use of `any` type here is not ideal, it does address the underlying issue of incorrect usage of the `FieldProps` type.
=> fix: override fieldType incorrect type

apps/docs/pages/docs/integrating-puck/multi-column-layouts.mdx
Documenting root DropZone behaviour as this is a gap. Closes #866.
=> docs: document root DropZone behaviour

apps/demo/config/blocks/Button/index.tsx, apps/docs/pages/docs/api-reference/fields/number.mdx, apps/docs/pages/docs/api-reference/fields/text.mdx, apps/docs/pages/docs/api-reference/fields/textarea.mdx, packages/core/components/AutoField/fields/DefaultField/index.tsx, packages/core/components/AutoField/fields/TextareaField/index.tsx, packages/core/types/Fields.ts
=> feat: placeholder param for text, textarea, number fields

packages/core/components/AutoField/fields/ArrayField/index.tsx
This PR is intended to fix a bug with the file-type field.
It's possible that `e.preventDefault()` in onClick was addressing some issue, but during local testing, I didn't notice any changes in the behavior of the array-type field. Clicking on the file-type field works as expected.
Closes #933
=> fix: input file on component type array not working

packages/core/components/AutoField/index.tsx
When modifying array elements, values were reset in some cases.
Closes #951
https://github.com/user-attachments/assets/312b0ef6-cbce-4901-ab39-331c4c43c14c
=> fix: when updating a field in one array item, other items unexpectedly reset or change

packages/core/components/AutoField/fields/ArrayField/index.tsx, packages/core/components/Sortable/index.tsx
This PR fixes an issue with sorting elements in an array-type field, where a moved element was always bound to the first container.
Closes #940
=> fix: reordering items in array fields

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
This PR adds helpful links to Discord and GitHub Discussions for questions and support, and also introduces an issue template specifically for reporting bugs.
=> Add issue template for bug reports on GitHub

packages/core/components/DragDropContext/index.tsx, packages/core/components/Drawer/index.tsx, packages/core/package.json, yarn.lock
Some slip-ups in 0.18 resulted in the unintentional dropping of React 17. Changes:
1. Use internal `useSafeId` instead of `useId`
2. Downgrade zustand from v5 to v4.5.6, as v5 drops React 17 support
Closes #960
=> fix: restore React 17 compatability

packages/core/components/Puck/index.tsx
While testing the canary release, I encountered the issue below in our project.
[Context as Provider](https://react.dev/blog/2024/12/05/react-19#context-as-a-provider) is only available in React 19.
=> fix: use of `UsePuckStoreContext` is not compatible with previous react versions (<19)

apps/docs/pages/docs/api-reference/functions/use-puck.mdx
Fixes a broken link to the selector function documentation in the `usePuck` docs.
=> docs: fix broken link

apps/docs/pages/docs/api-reference/fields/base.mdx
Fixes a broken link to the `labelIcon` section in the Fields Base docs.
=> docs: fix broken link in fields Base docs

apps/docs/pages/docs/api-reference/puck-api.mdx
Adds documentation details and links specifying what the new item selector getters return.
=> docs: clarify return values of item selector getters

packages/core/lib/use-puck.ts
Fixes a small typing issue in `UsePuckData` where the non typed `Config` is returned for `config` instead of the typed `UserConfig`
=> fix: typing issue in UsePuckData

apps/docs/pages/docs/api-reference/data-model/component-data.mdx
Fixes broken links in the table of contents of the `ComponentData` documentation.
=> docs: fix broken links in ComponentData docs

packages/core/components/DragDropContext/index.tsx, packages/core/components/DraggableComponent/index.tsx, packages/core/components/DropZone/context.tsx, packages/core/components/DropZone/index.tsx, packages/core/components/DropZone/lib/use-content-with-preview.ts, packages/core/components/DropZone/lib/use-min-empty-height.ts, packages/core/components/DropZone/styles.module.css, packages/core/components/LayerTree/index.tsx, packages/core/components/Puck/components/Fields/index.tsx, packages/core/components/Puck/components/Header/index.tsx, packages/core/components/Puck/components/Header/styles.module.css, packages/core/components/Puck/index.tsx, packages/core/components/Puck/styles.module.css, packages/core/index.ts, packages/core/lib/dnd/use-on-drag-finished.ts, packages/core/lib/use-slots.tsx, packages/core/lib/use-why-render.ts, packages/core/package.json, packages/core/store/slices/__tests__/nodes.spec.tsx, packages/core/store/slices/nodes.ts, yarn.lock
Blockers:
* #896
* https://github.com/clauderic/dnd-kit/issues/1701
---
Further identified rendering improvements:
Closes #644
=> Further performance improvements

packages/core/types/Fields.ts
Quick one that I noticed when reviewing another PR, `objectFields` were always `any`. Same with `getItemSummary` on external fields.
=> fix: type object, array, and external field types correctly

apps/docs/components/Preview/index.tsx, apps/docs/pages/docs/api-reference/functions/register-overlay-portal.mdx, apps/docs/pages/docs/integrating-puck/overlay-portals.mdx, packages/core/bundle/core.ts, packages/core/components/DraggableComponent/index.tsx, packages/core/components/Puck/components/Canvas/index.tsx, packages/core/components/Puck/components/Preview/index.tsx, packages/core/lib/overlay-portal/index.tsx, packages/core/lib/overlay-portal/styles.css
Add overlay portals via a new `registerOverlayPortal` API. Overlay portals enable parts of the component to be punch-through the overlay, enabling targeted interactivity.
This will enable inline content editing (often conflated with rich text), amongst other functionality.
https://github.com/user-attachments/assets/020a5ec9-881e-4b8d-9a72-f49122829b76
```tsx
import { registerOverlayPortal } from "@measured/puck";
const MyComponent = () => {
const ref = useRef<HTMLDivElement>(null);
useEffect(() => registerOverlayPortal(ref.current), [ref.current]);
return <button ref={ref}>Clickable</button>
}
```
=> feat: add overlay portals for UI beneath overlay

packages/core/types/Config.tsx, packages/core/types/Internal.tsx
Type issues with functions were observed in test files (which weren't failing on build) when using custom root configs.
This restores original functionality for root.
=> fix: address type issues when using root

packages/plugin-emotion-cache/package.json
Add a missing `"require"` entry to the `exports` map in `package.json`.  
This fixes `ERR_PACKAGE_PATH_NOT_EXPORTED` errors when requiring  
`@measured/puck-plugin-emotion-cache` in CommonJS environments (e.g. Cypress component tests).
=> fix: add CommonJS export to emotion cache package.json

packages/core/components/DropZone/index.tsx, packages/core/lib/data/__tests__/flatten-data.spec.tsx, packages/core/lib/data/flatten-data.ts
Resolves #1198 
@chrisvxd not sure if this is the correct place to have this but I've added resolve permissions to the dropzone so that component permissions are resolved even if they are in a slot.
=> fix: resolve permissions in drop zone so that slots maintain permissions

packages/core/components/InlineTextField/styles.module.css
Per CSS especification, `inline-block` elements don't inherit text decoration styles. This leads to any text decoration applied to inline editable fields to be ignored.
To fix this, this PR includes an explicit inheritance of the text decoration in the inline text field component.
Closes #1336
=> Inherit text decoration styles in the inline text field

apps/docs/pages/docs/api-reference/data-model/data.mdx, apps/docs/pages/docs/api-reference/data-model/item-selector.mdx, apps/docs/pages/docs/api-reference/functions/walk-tree.mdx
It appears that there isn't a `/docs/api-reference/fields/slots` documentation page at the moment so readers encounter 404 errors.  The `/docs/api-reference/fields/slot` seems like the closest approximation to what the author intends.  Feedback welcome.
=> docs: update broken links to slots documentation

packages/core/lib/overlay-portal/index.tsx
The `disableDrag` option from `registerOverlayPortal` had no effect if `disableDragOnFocus` was also enabled. This happened because of the order of the `if` checks inside `registerOverlayPortal`: `disableDragOnFocus` always took precedence over `disableDrag`.
- Reordered the checks so that `disableDrag` is evaluated first. If `disableDrag` is enabled, its handling runs. If not, then the `disableDragOnFocus` handling runs.  
- Fixed another bug in the cleanup function: the `onFocus` callback was incorrectly removed for the `blur` event instead of `onBlur`.
- Enabling the `disableDrag` option in `registerOverlayPortal` now correctly disables dragging components when dragging within the portal.  
- Disabling `disableDrag` and:  
- Enabling `disableDragOnFocus` disables dragging when focusing …
=> Check for `disableDrag` first instead of `disableDragOnFocus`

recipes/next/middleware.ts
Fixes #1361.
Ideally we would upgrade Next.js to the patched version but I've opted for the more immediate solution for now.
=> fix: add request to NextResponse.next
